spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-oo7znnss.sql.tencentcdb.com:25732/xiaochao
    username: root
    password: Yw2984576321
  # session失效时间
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api